name: etravel
description: A new Flutter project.

publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.19.5 <3.0.0"

dependencies:
  cached_network_image: ^3.2.3
  country_picker: ^2.0.20
  cupertino_icons: ^1.0.5
  dio: ^5.1.2
  flutter:
    sdk: flutter
  flutter_config: ^2.0.0
  flutter_facebook_auth: ^5.0.11
  flutter_google_places: ^0.3.0
  flutter_native_splash: ^2.2.19
  flutter_polyline_points: ^1.0.0
  flutter_secure_storage: ^8.0.0
  flutter_stripe: ^9.2.0
  geocoding: ^2.1.0
  geolocator: ^9.0.2
  get: ^4.6.5
  google_api_headers: ^1.6.0
  google_maps_flutter: ^2.2.6
  google_maps_webservice: ^0.0.20-nullsafety.5
  google_sign_in: ^6.1.0
  http: ^0.13.6
  pin_code_fields: ^7.4.0

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/images/
    - assets/logo/
flutter_native_splash:
  color: "#29B973"
  image: assets/logo/logo.png

  android_12:
    color: "#29B973"
    image: assets/logo/logo.png
